      allocate( elem(3,nt) )
      allocate( edge(2,nemax) )
      allocate( tedge(2,nemax) )
      allocate( vedge(2,nemax) )
      allocate( esue(3,nt) )
      allocate( ptype(np) )
      allocate( coord(2,np) )
      allocate( qc(nvar,nt) )
      allocate( qcd(nvar,nt) )
      allocate( qcold(nvar,nt) )
      allocate( dt(nt) )
      allocate( af(3,np) )
      allocate( qv(nvar,np) )
      allocate( tarea(nt) )
      allocate( varea(np) )
      allocate( drmin(nt) )
      allocate( res(nvar,nt) )
      allocate( qx(3,np) )
      allocate( qy(3,np) )


c     Variables for gmres, see gmres.h
      allocate( ja(4*nvar*nvar*nt) )
      allocate( ia(nvar*nt+1) )
      allocate( jlu(4*nvar*nvar*nt) )
      allocate( ju(nvar*nt+1) )
      allocate( levs(nvar*nt) )
      allocate( jw(3*nvar*nt) )
      allocate( jmat(4*nvar*nvar*nt) )
      allocate( alu(4*nvar*nvar*nt) )
      allocate( w(nvar*nt) )
